# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/oyster_segmentation_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: root
#     password: 032466
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081